bot/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import event

urlpatterns = [
    path('', event),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('users/', include('users.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import  UserLoginView

app_name = 'users'

urlpatterns = [
    # path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login')
    ]

templates/all_students_list.html
{% extends 'base.html' %}


{% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css">

    <style>
        .container {
            width: 1024px;
            padding: 2em;
        }

        .bold-blue {
            font-weight: bold;
            color: #0277BD;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="container">

{#        <div id="toolbar">#}
{#            <select class="form-control">#}
{#                <option value="">Export Basic</option>#}
{#                <option value="all">Export All</option>#}
{#                <option value="selected">Export Selected</option>#}
{#            </select>#}
{#        </div>#}

        <table id="table"
               data-toggle="table"
               data-search="true"
               data-filter-control="true"
               data-show-export="true"
               data-click-to-select="true"
               data-toolbar="#toolbar">
            <thead>
            <tr>
                <th data-field="state" data-checkbox="true"></th>
{#                <th data-field="prenom" data-filter-control="input" data-sortable="true">Prénom</th>#}
{#                <th data-field="date" data-filter-control="select" data-sortable="true">Date</th>#}
{#                <th data-field="examen" data-filter-control="select" data-sortable="true">Examen</th>#}
{#                <th data-field="note" data-sortable="true">Note</th>#}
                    <th scope="col">Studentlar</th>

                    <th scope="col">Talaba bali</th>

                    <th scope="col">Ota bal</th>

                    <th scope="col">Ona bali</th>
                    <th data-field="Guruxi" data-filter-control="select" data-sortable="true" scope="col">Guruxi</th>
                    <th data-field="Gurux sanasi" data-filter-control="select" data-sortable="true" scope="col">Gurux sanasi</th>
            </tr>
            </thead>
            <tbody>
{#            <tr>#}
{#                <td class="bs-checkbox "><input data-index="0" name="btSelectItem" type="checkbox"></td>#}
{#                <td>Valérie</td>#}
{#                <td>01/09/2015</td>#}
{#                <td>Français</td>#}
{#                <td>12/20</td>#}
{#            </tr>#}
            {% for st in students %}
                    <tr>
                    <td class="bs-checkbox "><input data-index="{{ st.id }}" name="btSelectItem" type="checkbox"></td>
                        <td>
                            <a href="{% url 'single_stu' st.id %}">{{ st.firstName }} {{ st.lastName }} {{ st.secondName }}</a>
                        </td>
                        <td class="text-center">
                            {{ st.all_score_f_self }}
                        </td>
                        <td class="text-center">
                            {{ st.all_score_f_dad }}
                        </td>
                        <td class="text-center">
                            {{ st.all_score_f_mom }}
                        </td>
                        <td class="text-center">
                            {{ st.group.name }}
                        </td>
                        <td class="text-center">
                            {{ st.group.created_at }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block js %}

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script>
    <!-- Latest compiled and minified Locales -->
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/locale/bootstrap-table-zh-CN.min.js"></script>


    <script>
        $(screen).ready(function () {
              $('input.search-input').attr("placeholder", "isim");
        })
        //exporte les données sélectionnées
        var $table = $('#table');
        $(function () {
            $('#toolbar').find('select').change(function () {
                $table.bootstrapTable('refreshOptions', {
                    exportDataType: $(this).val()
                });
            });
        })

        var trBoldBlue = $("table");

        $(trBoldBlue).on("click", "tr", function () {
            $(this).toggleClass("bold-blue");
        });
    </script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.css' %}">

    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% block css %}
{% endblock %}
</head>
<body style=" ">

{% block content %}

{% endblock content %}

<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'jquery-3.6.0.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.min.js" integrity="sha512-Wt1bJGtlnMtGP0dqNFH1xlkLBNpEodaiQ8ZN5JLA5wpc1sUlk/O5uuOMNgvzddzkpvZ9GLyYNa8w2s7rqiTk5Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% block js %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="d-flex justify-content-between my-2">
            <div class="h2">Guruhlar</div>
            <div class="">
                <a class="btn btn-info" href="{% url 'all_students' %}">barcha talabalar</a>
            </div>
            <div class="">
                <a class="btn btn-primary" href="/admin/">admin</a>
            </div>

        </div>




        <table class="table table-striped" style="">
            <thead>
            <tr>

                <th scope="col">Guruh</th>
                <th scope="col">Yosh</th>
                <th scope="col">Kunlar</th>
                <th scope="col">Soat</th>
                <th scope="col"></th>


            </tr>
            </thead>
            <tbody>
            {% for gr in groups %}
            <tr>

                    <td><a href="{% url 'students' gr.id %}">{{ gr.name }}</a></td>
                    <td><a href="{% url 'students' gr.id %}">{{ gr.yosh }}</a></td>
                    <td><a href="{% url 'students' gr.id %}">{{ gr.kunlar }}</a></td>
                    <td><a href="{% url 'students' gr.id %}">{{ gr.soat }}</a></td>
                    <td><a class="btn btn-light " href="{% url 'task_list' gr.id %}">Topshiriqlar</a></td>
{#                    <td>Otto</td>#}

            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-warning text-center" role="alert">
            {{message}}
        </div>
    {% endfor %}
{% endif %}
<div style="min-height: 60vh">
    <div class="row w-100 mt-5 pt-5 justify-content-center">
        <div class="col-md-6 d-flex flex-column justify-content-center align-items-center border w-100 px-5 mb-5 con">
            {{errors}}
            <form action="{% url 'users:login' %}" method="post" class="w-100 d-flex flex-column">
                {% csrf_token %}
                <h4 class="reg text-center pt-5">{% trans '' %}</h4>
                <div class="d-lg-flex w-100 align-items-center mt-3">
                    <label for="id_email" class="mr-5 k" style="min-width: 135px; margin-right:34px!important;">{% trans 'username' %}</label>
                    {{form.username}}
                </div>
                <small class="text-danger align-self-end">{{form.email.errors}}</small>
    
                <div class="d-lg-flex w-100 align-items-center mt-3">
                    <label for="id_password" class="mr-5 k"
                        style="min-width: 135px; margin-right:34px!important;">{% trans 'password' %}</label>
                    {{form.password}}
                </div>
                <small class="text-danger align-self-end">{{form.password.errors}}</small>
                <div class="d-flex w-100 align-items-center mt-5 justify-content-between mb-5">
{#                    <small><a href="{% url 'users:register' %}" class="k">{% trans 'Регистрация' %}</a></small>#}
                    <button type="submit" class="sign-up btn-secondary btn text-white font-weight-bold k">{% trans 'Вход' %}</button>
{#                    <small><a href="{% url 'reset_password' %}" class="k">{% trans 'забыл пароль?' %}</a></small>#}
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

templates/single_page.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-6">
                <h2>Student</h2>
                <div class="d-flex border p-2 justify-content-between">
                    <div>First Name</div>
                    <div>{{ student.firstName }}</div>
                </div>
                <div class="d-flex border p-2 justify-content-between">
                    <div>LastName</div>
                    <div>{{ student.lastName }}</div>
                </div>
                <div class="d-flex border p-2 justify-content-between">
                    <div>SecondName</div>
                    <div>{{ student.secondName }}</div>
                </div>
                <div class="d-flex border p-2 justify-content-between">
                    <div>Address</div>
                    <div>{{ student.address }}</div>
                </div>
                <div class="d-flex border p-2 justify-content-between">
                    <div>Phone</div>
                    <div>{{ student.self_telegram.phone }}</div>
                </div>
                <div class="d-flex border p-2 justify-content-between">
                    <div>Group</div>
                    <div>{{ student.group }}</div>
                </div>
                <div class="d-flex border p-2 justify-content-center">
                    <img class="img-fluid" width="300px" src="{{ student.self_telegram.photo.url }}">
                </div>


            </div>
            <div class="col-6">
                <div class="row mb-5">

                    <div class="col-6">
                        <h2>{{ student.dad_telegram.role_name }}</h2>
                        <div class="d-flex border p-2 justify-content-between">
                            <div>First Name</div>
                            <div>{{ student.dad_telegram.firstName }}</div>
                        </div>
                        <div class="d-flex border p-2 justify-content-between">
                            <div>LastName</div>
                            <div>{{ student.dad_telegram.lastName }}</div>
                        </div>
                        <div class="d-flex border p-2 justify-content-between">
                            <div>SecondName</div>
                            <div>{{ student.dad_telegram.secondName }}</div>
                        </div>
                        <div class="d-flex border p-2 justify-content-between">
                            <div>Address</div>
                            <div>{{ student.dad_telegram.address }}</div>
                        </div>
                        <div class="d-flex border p-2 justify-content-between">
                    <div>Phone</div>
                    <div>{{ student.dad_telegram.phone }}</div>
                </div>
                    </div>
                    <div class="col-6">
                        <img class="img-fluid" width="200px" src="{{ student.dad_telegram.photo.url }}">
                    </div>
                </div>
                <div class="row">

                    <div class="col-6">
                        <h2>{{ student.mom_telegram.role_name }}</h2>
                        <div class="d-flex border p-2 justify-content-between">
                            <div>First Name</div>
                            <div>{{ student.mom_telegram.firstName }}</div>
                        </div>
                        <div class="d-flex border p-2 justify-content-between">
                            <div>LastName</div>
                            <div>{{ student.mom_telegram.lastName }}</div>
                        </div>
                        <div class="d-flex border p-2 justify-content-between">
                            <div>SecondName</div>
                            <div>{{ student.mom_telegram.secondName }}</div>
                        </div>
                        <div class="d-flex border p-2 justify-content-between">
                            <div>Address</div>
                            <div>{{ student.mom_telegram.address }}</div>
                        </div>
                        <div class="d-flex border p-2 justify-content-between">
                    <div>Phone</div>
                    <div>{{ student.mom_telegram.phone }}</div>
                </div>
                    </div>
                    <div class="col-6">
                        <img class="img-fluid" width="200px" src="{{ student.mom_telegram.photo.url }}">
                    </div>
                </div>
            </div>
        </div>
{#        <div class="my-3"><a class="btn btn-block btn-dark text-light">asdas</a></div>#}
    </div>



    <div class="container my-3">
    <canvas id="line-chart" width="800" height="350"></canvas>
    </div>



<div id="man" style="display: none">{{ student.dad_telegram.role_name|safe }}</div>
<div id="woman"  style="display: none">{{ student.mom_telegram.role_name|safe }}</div>
<div></div>
{% endblock %}
{% block js %}
    <script>
    var woman = $('#woman').html();
    var man = $('#man').html();
    var date = {{ date_list|safe }};
    var self = {{ self_list|safe }};
    var mom = {{ mom_list|safe }};
    var dad = {{ dad_list|safe }};
   new Chart(document.getElementById("line-chart"), {
  type: 'line',
  data: {
    labels: date,
    datasets: [{
        data: self,
        label: "Talaba",
        borderColor: "#3e95cd",
        fill: false
      }, {
        data: dad,
        label: man,
        borderColor: "#8e5ea2",
        fill: false
      }, {
        data: mom,
        label: woman,
        borderColor: "#3cba9f",
        fill: false
      }
    ]
  },
  options: {
    title: {
      display: true,
      text: 'World population per region (in millions)'
    }
  }
});
    </script>
{% endblock %}

templates/students.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="d-flex justify-content-between my-2">
            <div class="h2">Studentlar</div>
            <div class="h2">{{ groups.name }}</div>
            <div class="h2">talabalar: {{ students|length }}</div>
            <div class="">
                <a class="btn btn-primary" href="/admin/">admin</a>
            </div>
        </div>
        <form method="post" action="{% url 'change' groups.id %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Kunlik topshiriqlari</label>
                <textarea name="tasks" class="form-control" id="exampleFormControlTextarea1"
                          rows="3">{{ groups.dailyTask }}</textarea>
            </div>
            <button type="submit" class="btn btn-success mb-2">Saqlash</button>
        </form>
        <table class="table table-striped" style="">
            <thead>
            <tr>
                <th scope="col">Studentlar</th>

                <th scope="col">O'zining umumiy bali</th>

                <th scope="col">Otaning umumiy bali</th>

                <th scope="col">Onasining umumiy bali</th>
            </tr>
            </thead>
            <tbody>
            {% for st in students %}
                <tr>
                    <td>
                        <a href="{% url 'single_stu' st.id %}">{{ st.firstName }} {{ st.lastName }} {{ st.secondName }}</a>
                    </td>
                    <td class="text-center">
                        {{ st.all_score_f_self }}
                    </td>
                    <td class="text-center">
                        {{ st.all_score_f_dad }}
                    </td>
                    <td class="text-center">
                        {{ st.all_score_f_mom }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/tasks_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="d-flex justify-content-between my-2" >
            <div class="h2">Topshiriqlar</div>
            <div class="h2">{{ groups.name }}</div>
            <div class="">
                <a class="btn btn-primary" href="/admin/">admin</a>
            </div>

        </div>

        {% for student in students %}
            <div class="h4 text-secondary"><a href="{% url 'single_stu' student.id %}">{{ student.firstName }} {{ student.lastName }}</a></div>
            <div style="overflow-x: scroll !important;" class="my-3">
            <table class="table table-bordered "  >
                <thead >
                <tr>
                    <th scope="col">#</th>
                    {% for i in tasks %}
                        <th scope="col" style="white-space: nowrap">{{ i.created_day.date }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">Talaba</th>
                    {% for score in answers %}
                        {% if score.student == student %}
                            <td>{{ score.score_fs }}</td>
                            {% else %}
                            <td>none</td>
                        {% endif %}
                    {% endfor %}


                </tr>
                <tr>
                    <th scope="row">{{ student.mom_telegram.role_name }}</th>
                    {% for score in answers %}
                        {% if score.student == student %}
                            <td>{{ score.score_fmom }}</td>
                        {% else %}
                            <td>none</td>
                        {% endif %}
                    {% endfor %}
                </tr>
                <tr>
                    <th scope="row">{{ student.dad_telegram.role_name }}</th>
                    {% for score in answers %}
                        {% if score.student == student %}
                            <td>{{ score.score_fdad }}</td>
                        {% else %}
                            <td>none</td>
                        {% endif %}
                    {% endfor %}
                </tr>
                </tbody>
            </table>
            </div>
        {% endfor %}


    </div>
{% endblock %}